### ISSUE TITLE
cabal-rpm returns on stderr warning if isn't found dep.

### ISSUE THREAD

**Issue by mimi1vx** [opensuse-haskell/cabal2obs#1]
https://github.com/opensuse-haskell/cabal-rpm/issues/1 

it needs monitor stderr in cabal-rpm run and react to https://github.com/opensuse-haskell/cabal-rpm/blob/master/src/Dependencies.hs#L97. 

--> print warning for this package or save log with package + needed dep

**Comment by peti** [comment]
I felt that it makes more sense for cabal-rpm to fail when it cannot produce a correct spec file. That way, cabal2obs does not have to treat that tool differently than any other command we run and expect the return code to signal failure. Implemented in to03d90524f4d7cd70e31e52e7ad862bb84f76e51a.
